

## server
server:
  port: 8081


spring:
    
    
  ## datasource[h2]
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: root
    password: rootpass!


### datasource[mariadb]
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://211.254.212.105:32300/test?serverTimezone=Asia/Seoul
#    username: root
#    password: rootpass!

  ## redis
  redis:
    lettuce:
      pool:
        max-active: 8   # pool에 할당할수 있는 커넥션 최대수(default:8)
        max-idle: 8     # pool의 idle 커넥션 최대수(default:8)
        min-idle: 0     # pool의 idle 커넥션 최소수(default:0)
    host: 211.254.212.105  # 
    port: 32200
    password: 'new1234'


  ## JPA Properties
  #update the schema with the given values.
  jpa:
    hibernate:
      ddl-auto: update      
    properties:
      hibernate:
        format_sql: true  #To beautify or pretty print the SQL
        show-sql: false   #show sql






